### ISSUE TITLE
0.0.7不能正常使用

### ISSUE THREAD

**Issue by NorDorado** [susiwen8/echarts-vscode-extension#16]
F1键入echarts后 提示not command echarts-extend ，0.0.6正常 vscode版本 1.4.1 语言简体中文

**Comment by susiwen8** [comment]
谢谢反馈，我查看下

**Comment by susiwen8** [comment]
@NorDorado 我把这个命令移除了，现在是检测到是js文件就自动激活。后期应该会加回这个命令。谢谢反馈，待会发一个0.0.8版本

**Comment by susiwen8** [comment]
@NorDorado 0.0.8版本已发布

**Comment by NorDorado** [comment]
收到，我更新下哈哈
